development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:2e9630698c3076d378752e18f111fae0@dory.redistogo.com:11451/
  channel_prefix: vicinux_production
